//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivs.Resources.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ivs.Resources.Resource.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string COM_LBL_ADD {
            get {
                return ResourceManager.GetString("COM_LBL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string COM_LBL_BACK {
            get {
                return ResourceManager.GetString("COM_LBL_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string COM_LBL_CANCEL {
            get {
                return ResourceManager.GetString("COM_LBL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string COM_LBL_CLOSE {
            get {
                return ResourceManager.GetString("COM_LBL_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string COM_LBL_COPY {
            get {
                return ResourceManager.GetString("COM_LBL_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string COM_LBL_DELETE {
            get {
                return ResourceManager.GetString("COM_LBL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string COM_LBL_DETAIL {
            get {
                return ResourceManager.GetString("COM_LBL_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string COM_LBL_EDIT {
            get {
                return ResourceManager.GetString("COM_LBL_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string COM_LBL_ENGLISH {
            get {
                return ResourceManager.GetString("COM_LBL_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string COM_LBL_EXPORT {
            get {
                return ResourceManager.GetString("COM_LBL_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string COM_LBL_IMPORT {
            get {
                return ResourceManager.GetString("COM_LBL_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string COM_LBL_JAPANESE {
            get {
                return ResourceManager.GetString("COM_LBL_JAPANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string COM_LBL_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("COM_LBL_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string COM_LBL_MS_ITEM_CODE {
            get {
                return ResourceManager.GetString("COM_LBL_MS_ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        internal static string COM_LBL_MS_ITEM_GROUPCODE {
            get {
                return ResourceManager.GetString("COM_LBL_MS_ITEM_GROUPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string COM_LBL_MS_ITEM_GROUPNAME {
            get {
                return ResourceManager.GetString("COM_LBL_MS_ITEM_GROUPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv Unit Code.
        /// </summary>
        internal static string COM_LBL_MS_ITEM_INVUNITCODE {
            get {
                return ResourceManager.GetString("COM_LBL_MS_ITEM_INVUNITCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name (VN).
        /// </summary>
        internal static string COM_LBL_MS_ITEM_NAME1 {
            get {
                return ResourceManager.GetString("COM_LBL_MS_ITEM_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name (EN).
        /// </summary>
        internal static string COM_LBL_MS_ITEM_NAME2 {
            get {
                return ResourceManager.GetString("COM_LBL_MS_ITEM_NAME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string COM_LBL_MS_UNIT_CONVERT_FACTOR {
            get {
                return ResourceManager.GetString("COM_LBL_MS_UNIT_CONVERT_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Unit.
        /// </summary>
        internal static string COM_LBL_MS_UNIT_CONVERT_FROM_UNIT {
            get {
                return ResourceManager.GetString("COM_LBL_MS_UNIT_CONVERT_FROM_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Unit.
        /// </summary>
        internal static string COM_LBL_MS_UNIT_CONVERT_TO_UNIT {
            get {
                return ResourceManager.GetString("COM_LBL_MS_UNIT_CONVERT_TO_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string COM_LBL_NO {
            get {
                return ResourceManager.GetString("COM_LBL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string COM_LBL_OK {
            get {
                return ResourceManager.GetString("COM_LBL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string COM_LBL_PRINT {
            get {
                return ResourceManager.GetString("COM_LBL_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string COM_LBL_REFRESH {
            get {
                return ResourceManager.GetString("COM_LBL_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string COM_LBL_SAVE {
            get {
                return ResourceManager.GetString("COM_LBL_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Next.
        /// </summary>
        internal static string COM_LBL_SAVEANDNEXT {
            get {
                return ResourceManager.GetString("COM_LBL_SAVEANDNEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string COM_LBL_SEARCH {
            get {
                return ResourceManager.GetString("COM_LBL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string COM_LBL_VIETNAMESE {
            get {
                return ResourceManager.GetString("COM_LBL_VIETNAMESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string COM_LBL_YES {
            get {
                return ResourceManager.GetString("COM_LBL_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Access deniable..
        /// </summary>
        internal static string COM_MSG_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("COM_MSG_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97-{0} failed..
        /// </summary>
        internal static string COM_MSG_ACT_FAILED {
            get {
                return ResourceManager.GetString("COM_MSG_ACT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97-{0} successfully..
        /// </summary>
        internal static string COM_MSG_ACT_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_ACT_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97-{0} successfully: {1} Rows..
        /// </summary>
        internal static string COM_MSG_ACT_SUCCESSFULLY_AND_ROWS {
            get {
                return ResourceManager.GetString("COM_MSG_ACT_SUCCESSFULLY_AND_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-{0} must be between {1} and {2}..
        /// </summary>
        internal static string COM_MSG_BETWEEN {
            get {
                return ResourceManager.GetString("COM_MSG_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-Can&apos;t print over {0} times..
        /// </summary>
        internal static string COM_MSG_CAN_NOT_PRINT {
            get {
                return ResourceManager.GetString("COM_MSG_CAN_NOT_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Cancel successfully..
        /// </summary>
        internal static string COM_MSG_CANCEL_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_CANCEL_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-It is out of date..
        /// </summary>
        internal static string COM_MSG_CONCURRENCY_VIOLATION {
            get {
                return ResourceManager.GetString("COM_MSG_CONCURRENCY_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to [{0}]?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_ACT {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to cancel?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_CANCEL {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear all data?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_CLEAR {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to close this period?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_CLOSE {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to delete?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to disconnect?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_DISCONNECT {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Information has been changed. Do you want to save before exit?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_EXIT {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Are you sure you want to lock this period?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_LOCK {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to open this period?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_OPEN {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to print?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_PRINT {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Are you sure you want to process?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_PROCESS {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to save?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_SAVE {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Are you sure you want to unlock this period?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_UNLOCK {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Connection has been lost..
        /// </summary>
        internal static string COM_MSG_CONNECTION_LOST {
            get {
                return ResourceManager.GetString("COM_MSG_CONNECTION_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Period {0} wasn&apos;t inputed Unit Price yet..
        /// </summary>
        internal static string COM_MSG_CURRENT_PERIOD_NOT_ENTRY_PRICE {
            get {
                return ResourceManager.GetString("COM_MSG_CURRENT_PERIOD_NOT_ENTRY_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Can&apos;t edit {0}, data being in used..
        /// </summary>
        internal static string COM_MSG_DATA_BEING_USED {
            get {
                return ResourceManager.GetString("COM_MSG_DATA_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-No data input/output, you cannot close this period..
        /// </summary>
        internal static string COM_MSG_DATA_IN_OUT_NOT_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_DATA_IN_OUT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The data hasn&apos;t found..
        /// </summary>
        internal static string COM_MSG_DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit [{1}] of [{0}], data is being in used. .
        /// </summary>
        internal static string COM_MSG_DATA_OF_BEING_USED {
            get {
                return ResourceManager.GetString("COM_MSG_DATA_OF_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The [{0}] hasn&apos;t found..
        /// </summary>
        internal static string COM_MSG_DATA_OR_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_DATA_OR_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The deadlock has Found..
        /// </summary>
        internal static string COM_MSG_DEADLOCK_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_DEADLOCK_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Delete successfully..
        /// </summary>
        internal static string COM_MSG_DELETE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_DELETE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Disconnect successfully..
        /// </summary>
        internal static string COM_MSG_DISCONNECT_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_DISCONNECT_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The data is already exist. Please input other!.
        /// </summary>
        internal static string COM_MSG_DUPPLICATE_KEY {
            get {
                return ResourceManager.GetString("COM_MSG_DUPPLICATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] is already exist..
        /// </summary>
        internal static string COM_MSG_EXISTED {
            get {
                return ResourceManager.GetString("COM_MSG_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not export for this category!.
        /// </summary>
        internal static string COM_MSG_EXPORT_NOT_FLOW {
            get {
                return ResourceManager.GetString("COM_MSG_EXPORT_NOT_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Export successfully!.
        /// </summary>
        internal static string COM_MSG_EXPORT_SUCCESSFULLY1 {
            get {
                return ResourceManager.GetString("COM_MSG_EXPORT_SUCCESSFULLY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: {1} must be fill in and greater than {2}..
        /// </summary>
        internal static string COM_MSG_FACTOR_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_FACTOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Can&apos;t access the file [{0}], this file being in used by other process..
        /// </summary>
        internal static string COM_MSG_FILE_BEING_USED {
            get {
                return ResourceManager.GetString("COM_MSG_FILE_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-File&apos;s format is invalid..
        /// </summary>
        internal static string COM_MSG_FILE_FORMAT_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_FILE_FORMAT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Number of column is invalid..
        /// </summary>
        internal static string COM_MSG_FILE_NUM_OF_COLUMN_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_FILE_NUM_OF_COLUMN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Number of row is invalid..
        /// </summary>
        internal static string COM_MSG_FILE_NUM_OF_ROW_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_FILE_NUM_OF_ROW_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Foreign key not exist..
        /// </summary>
        internal static string COM_MSG_FOREIGN_KEY_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_FOREIGN_KEY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Can&apos;t be deleted, data being in use..
        /// </summary>
        internal static string COM_MSG_FOREIGN_KEY_VIOLATION {
            get {
                return ResourceManager.GetString("COM_MSG_FOREIGN_KEY_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-System exception occurred..
        /// </summary>
        internal static string COM_MSG_GENERAL_EXCEPTION {
            get {
                return ResourceManager.GetString("COM_MSG_GENERAL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] must be greater than [{1}]!.
        /// </summary>
        internal static string COM_MSG_GREATER_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] must be greater than or equal to [{1}]!.
        /// </summary>
        internal static string COM_MSG_GREATER_THAN_OR_EQUAL {
            get {
                return ResourceManager.GetString("COM_MSG_GREATER_THAN_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Shipping/Arriving items on grid {0} and grid {1} was dupplicated..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_DUPPLICATED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_DUPPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Grid [{0}]: Line [{1}]: [{2}] has already been existed..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_EXISTED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Grid {0}: Line {1} - [{2}] must be greater than [{3}]!.
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_GREATER_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Grid {0}: Line {1} - {2} is invalid..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Grid {0}: Line {1} - {2} must be fill in!.
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Transaction list on grid {0} must be fill in!.
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: [{1}] must be fill in..
        /// </summary>
        internal static string COM_MSG_GRID_INVENTORY_COUNTED_QTY_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_INVENTORY_COUNTED_QTY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Duplicated item list..
        /// </summary>
        internal static string COM_MSG_GRID_INVENTORY_DUPLICATED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_INVENTORY_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Item list must be fill in!.
        /// </summary>
        internal static string COM_MSG_GRID_INVENTORY_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_INVENTORY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line [{0}]: [{1}] has already been existed..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_EXISTED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-Line {0}: This is NG, QI, NC product..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_FG_NOT_OK {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_FG_NOT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: [{1}] must be greater than [{2}]!.
        /// </summary>
        internal static string COM_MSG_GRID_LINE_GREATER_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: {1} is invalid..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: [{1}] must be less than or equal [{2}]!.
        /// </summary>
        internal static string COM_MSG_GRID_LINE_LESS_THAN_OR_EQUAL {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_LESS_THAN_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-Line {0}: This is Free-product/ Product..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_PRODUCT_AND_FREE_PRODUCT {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_PRODUCT_AND_FREE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: {1} must be fill in!.
        /// </summary>
        internal static string COM_MSG_GRID_LINE_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-Line {0}: This is  WIP  product..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_WIP {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_WIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record {0} of {1}.
        /// </summary>
        internal static string COM_MSG_GRID_RECORD_OF_TOTAL {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_RECORD_OF_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Transaction list must be fill in!.
        /// </summary>
        internal static string COM_MSG_GRID_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Item has inventory..
        /// </summary>
        internal static string COM_MSG_HAS_INVENTORY {
            get {
                return ResourceManager.GetString("COM_MSG_HAS_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-The information has been changed. Do you want to save before exiting?.
        /// </summary>
        internal static string COM_MSG_HAVING_CHANGE {
            get {
                return ResourceManager.GetString("COM_MSG_HAVING_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        internal static string COM_MSG_HEADERGRID_DRAG {
            get {
                return ResourceManager.GetString("COM_MSG_HEADERGRID_DRAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: {1} column is invalid..
        /// </summary>
        internal static string COM_MSG_IMPORT_LINE_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_IMPORT_LINE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: {1} column doesn&apos;t exist..
        /// </summary>
        internal static string COM_MSG_IMPORT_LINE_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_IMPORT_LINE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Insert successfully!.
        /// </summary>
        internal static string COM_MSG_INSERT_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_INSERT_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Adjustment Date must be belong date in period..
        /// </summary>
        internal static string COM_MSG_INVALID_ADJUSTMENTDATE {
            get {
                return ResourceManager.GetString("COM_MSG_INVALID_ADJUSTMENTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Invalid {0}..
        /// </summary>
        internal static string COM_MSG_INVALID_DATA_OR_ACTION {
            get {
                return ResourceManager.GetString("COM_MSG_INVALID_DATA_OR_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Invalid Database..
        /// </summary>
        internal static string COM_MSG_INVALID_DATABASE {
            get {
                return ResourceManager.GetString("COM_MSG_INVALID_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Invalid Email Address..
        /// </summary>
        internal static string COM_MSG_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("COM_MSG_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Invalid Host..
        /// </summary>
        internal static string COM_MSG_INVALID_HOST {
            get {
                return ResourceManager.GetString("COM_MSG_INVALID_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-This invoice was canceled!.
        /// </summary>
        internal static string COM_MSG_INVOICE_CANCEL_FAIL_1 {
            get {
                return ResourceManager.GetString("COM_MSG_INVOICE_CANCEL_FAIL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The invoice number has not set yet..
        /// </summary>
        internal static string COM_MSG_INVOICE_CANCEL_FAIL_2 {
            get {
                return ResourceManager.GetString("COM_MSG_INVOICE_CANCEL_FAIL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-This invoice was not printed yet..
        /// </summary>
        internal static string COM_MSG_INVOICE_CANCEL_FAIL_3 {
            get {
                return ResourceManager.GetString("COM_MSG_INVOICE_CANCEL_FAIL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: Shipping quantity is not enough. DocumentNumber: {1}.
        /// </summary>
        internal static string COM_MSG_INVOICE_QUANTITY_NOT_ENOUGH {
            get {
                return ResourceManager.GetString("COM_MSG_INVOICE_QUANTITY_NOT_ENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-{0}&apos;s length is invalid..
        /// </summary>
        internal static string COM_MSG_LENGTH_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_LENGTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-{0}&apos;s maximum length is {1}..
        /// </summary>
        internal static string COM_MSG_LENGTH_MAXIMUM {
            get {
                return ResourceManager.GetString("COM_MSG_LENGTH_MAXIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] must be less than [{1}]!.
        /// </summary>
        internal static string COM_MSG_LESS_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] must be less than or equal to [{1}]!.
        /// </summary>
        internal static string COM_MSG_LESS_THAN_OR_EQUAL {
            get {
                return ResourceManager.GetString("COM_MSG_LESS_THAN_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Over timeout..
        /// </summary>
        internal static string COM_MSG_LOCK_WAIT_TIMEOUT_EXCEEDED {
            get {
                return ResourceManager.GetString("COM_MSG_LOCK_WAIT_TIMEOUT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] must be matched with [{1}]!.
        /// </summary>
        internal static string COM_MSG_MATCHED_PASSWORD {
            get {
                return ResourceManager.GetString("COM_MSG_MATCHED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-There are more than 1 selected row..
        /// </summary>
        internal static string COM_MSG_MORE_ONE_ROW_SELECTED {
            get {
                return ResourceManager.GetString("COM_MSG_MORE_ONE_ROW_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Department Code] must be fill in..
        /// </summary>
        internal static string COM_MSG_MS_DEPARTMENT_CODE {
            get {
                return ResourceManager.GetString("COM_MSG_MS_DEPARTMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Department Name (VN)] must be fill in..
        /// </summary>
        internal static string COM_MSG_MS_DEPARTMENT_NAME1 {
            get {
                return ResourceManager.GetString("COM_MSG_MS_DEPARTMENT_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Department Name (EN)] must be fill in..
        /// </summary>
        internal static string COM_MSG_MS_DEPARTMENT_NAME2 {
            get {
                return ResourceManager.GetString("COM_MSG_MS_DEPARTMENT_NAME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-{0} period is not lock..
        /// </summary>
        internal static string COM_MSG_NEXT_PERIOD_NOT_LOCK {
            get {
                return ResourceManager.GetString("COM_MSG_NEXT_PERIOD_NOT_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-{0} period is not unlock..
        /// </summary>
        internal static string COM_MSG_NEXT_PERIOD_NOT_UNLOCK {
            get {
                return ResourceManager.GetString("COM_MSG_NEXT_PERIOD_NOT_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-No row selected..
        /// </summary>
        internal static string COM_MSG_NO_ROW_SELECTED {
            get {
                return ResourceManager.GetString("COM_MSG_NO_ROW_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] not equal to [{1}]..
        /// </summary>
        internal static string COM_MSG_NOT_EQUAL {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-{0}] doesn&apos;t exist..
        /// </summary>
        internal static string COM_MSG_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The [{0}] isn&apos;t matched with the [{1}]..
        /// </summary>
        internal static string COM_MSG_NOT_MATCH {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-[{0}] does not match the [{1}]..
        /// </summary>
        internal static string COM_MSG_NOT_MATCH_WARNING {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_MATCH_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The previous period isn&apos;t closed, you can&apos;t open the current period..
        /// </summary>
        internal static string COM_MSG_NOT_OPEN_PERIOD {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_OPEN_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-You don’t have permission to edit system data..
        /// </summary>
        internal static string COM_MSG_NOT_PERMISSION_EDIT {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_PERMISSION_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-You don’t have permission to view..
        /// </summary>
        internal static string COM_MSG_NOT_PERMISSION_VIEW {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_PERMISSION_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-You can&apos;t open this period..
        /// </summary>
        internal static string COM_MSG_NOT_REOPEN_PERIOD {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_REOPEN_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Number of invoice detail on grid is invalid..
        /// </summary>
        internal static string COM_MSG_NUM_OF_ROW_INVOICE_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_NUM_OF_ROW_INVOICE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-You cannot unlock this period..
        /// </summary>
        internal static string COM_MSG_PERIOD_NOT_UNLOCK {
            get {
                return ResourceManager.GetString("COM_MSG_PERIOD_NOT_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Count Sheet was canceled..
        /// </summary>
        internal static string COM_MSG_PHYSICAL_CANCEL {
            get {
                return ResourceManager.GetString("COM_MSG_PHYSICAL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Count Sheet was completed..
        /// </summary>
        internal static string COM_MSG_PHYSICAL_COMPLETE {
            get {
                return ResourceManager.GetString("COM_MSG_PHYSICAL_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The previous period isn&apos;t closed..
        /// </summary>
        internal static string COM_MSG_PREVIOUS_PERIOD_NOT_CLOSE {
            get {
                return ResourceManager.GetString("COM_MSG_PREVIOUS_PERIOD_NOT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Print successfully..
        /// </summary>
        internal static string COM_MSG_PRINT_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_PRINT_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer name is invalid. Please check the printer settings..
        /// </summary>
        internal static string COM_MSG_PRINTER_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_PRINTER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Can not process this action. Action is not valid..
        /// </summary>
        internal static string COM_MSG_PROCESS_NOT_VALID {
            get {
                return ResourceManager.GetString("COM_MSG_PROCESS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Process successfully!.
        /// </summary>
        internal static string COM_MSG_PROCESS_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_PROCESS_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] must be fill in!.
        /// </summary>
        internal static string COM_MSG_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Item Code] must be fill in..
        /// </summary>
        internal static string COM_MSG_REQUIRED_MS_ITEM_CODE {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED_MS_ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Group Code] must be fill in..
        /// </summary>
        internal static string COM_MSG_REQUIRED_MS_ITEM_GROUPCODE {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED_MS_ITEM_GROUPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Inv Unit Code] must be fill in..
        /// </summary>
        internal static string COM_MSG_REQUIRED_MS_ITEM_INVUNITCODE {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED_MS_ITEM_INVUNITCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Item Name (VN)] must be fill in..
        /// </summary>
        internal static string COM_MSG_REQUIRED_MS_ITEM_NAME1 {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED_MS_ITEM_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Item Name (EN)] must be fill in..
        /// </summary>
        internal static string COM_MSG_REQUIRED_MS_ITEM_NAME2 {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED_MS_ITEM_NAME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}] must be select!.
        /// </summary>
        internal static string COM_MSG_REQUIRED_SELECT {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97-{0} row(s) has found..
        /// </summary>
        internal static string COM_MSG_ROW_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_ROW_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-RPC server is unavailable..
        /// </summary>
        internal static string COM_MSG_RPC_SERVER_UNAVAILABLE {
            get {
                return ResourceManager.GetString("COM_MSG_RPC_SERVER_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[{0}], [{1}] to the same period..
        /// </summary>
        internal static string COM_MSG_SAME_PERIOD {
            get {
                return ResourceManager.GetString("COM_MSG_SAME_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-The file size exceeds system&apos;s allowed limit ({0} KB). You can&apos;t save..
        /// </summary>
        internal static string COM_MSG_SIZE_LIMITED {
            get {
                return ResourceManager.GetString("COM_MSG_SIZE_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Arriving Date] must be fill in!.
        /// </summary>
        internal static string COM_MSG_STOCK_ARRIVING_DATE_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_ARRIVING_DATE_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-This document was existed invoice(s)..
        /// </summary>
        internal static string COM_MSG_STOCK_CANCEL_EXIST_INVOICE {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_CANCEL_EXIST_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Cancel failed..
        /// </summary>
        internal static string COM_MSG_STOCK_CANCEL_FAIL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_CANCEL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Document had related transactions. Can not cancel..
        /// </summary>
        internal static string COM_MSG_STOCK_CANCEL_RELATED_FAIL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_CANCEL_RELATED_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Customer] must be fill in!.
        /// </summary>
        internal static string COM_MSG_STOCK_CUSTOMER_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_CUSTOMER_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-This document was canceled!.
        /// </summary>
        internal static string COM_MSG_STOCK_DOCUMENT_CANCELED {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_DOCUMENT_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Document No] must be fill in!.
        /// </summary>
        internal static string COM_MSG_STOCK_DOCUMENT_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_DOCUMENT_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: [Production Line] isn&apos;t found..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: Don&apos;t allow negative stock..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_MINUS_NG {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_MINUS_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: Allow to negative stock..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_MINUS_OK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_MINUS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: Stock out amount is enough..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_OUT_ENOUGH {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_OUT_ENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: Stock out amount is lack..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_OUT_LACK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_OUT_LACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: [Production line] isn&apos;t exist in stock..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_PRODUCTION_LINE_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_PRODUCTION_LINE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: [Quality Status] isn&apos;t exist in stock..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_QUALITY_STATUS_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_QUALITY_STATUS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: Related document&apos;s date must be less than or equal to [DocumentDate].
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_RELATED_DOCUMENT_DATE_NOT_VALID {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_RELATED_DOCUMENT_DATE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: Item&apos;s quantity of related document is not valid..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_RELATED_DOCUMENT_QTY_NOT_VALID {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_RELATED_DOCUMENT_QTY_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-Line {0}: Safety stock is dangerous..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_SAFETY_DANGEROUS {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_SAFETY_DANGEROUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Line {0}: [Stock Type] isn&apos;t valid..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_STOCK_TYPE_NOT_VALID {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_STOCK_TYPE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Item Code] must be fill in!.
        /// </summary>
        internal static string COM_MSG_STOCK_ITEM_CODE_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_ITEM_CODE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Don&apos;t allow negative stock..
        /// </summary>
        internal static string COM_MSG_STOCK_MINUS_NG {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_MINUS_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97-Allow negative stock..
        /// </summary>
        internal static string COM_MSG_STOCK_MINUS_OK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_MINUS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97-Stock out amount is enough..
        /// </summary>
        internal static string COM_MSG_STOCK_OUT_ENOUGH {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_OUT_ENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Stock out amount is lack..
        /// </summary>
        internal static string COM_MSG_STOCK_OUT_LACK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_OUT_LACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Period] is closed..
        /// </summary>
        internal static string COM_MSG_STOCK_PERIOD_CLOSE {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PERIOD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Inventory period was locked..
        /// </summary>
        internal static string COM_MSG_STOCK_PERIOD_LOCK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PERIOD_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Period] doesn&apos;t exist..
        /// </summary>
        internal static string COM_MSG_STOCK_PERIOD_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PERIOD_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Period] doesn&apos;t exist..
        /// </summary>
        internal static string COM_MSG_STOCK_PERIOD_NOT_EXIST1 {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PERIOD_NOT_EXIST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96-Do you want to print?.
        /// </summary>
        internal static string COM_MSG_STOCK_PRINT_CONFIRM {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PRINT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-Safety stock is dangerous. Do you want to continue?.
        /// </summary>
        internal static string COM_MSG_STOCK_SAFETY_DANGEROUS {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_SAFETY_DANGEROUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Shipping Date] must be fill in!.
        /// </summary>
        internal static string COM_MSG_STOCK_SHIPPING_DATE_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_SHIPPING_DATE_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Supplier] must be fill in!.
        /// </summary>
        internal static string COM_MSG_STOCK_SUPPLIER_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_SUPPLIER_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Arriving Warehouse] must be fill in!.
        /// </summary>
        internal static string COM_MSG_STOCK_WAREHOUSE2_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_WAREHOUSE2_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-[Arriving Warehouse] doesn&apos;t exist..
        /// </summary>
        internal static string COM_MSG_STOCK_WAREHOUSE2_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_WAREHOUSE2_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Snapshot successfully!.
        /// </summary>
        internal static string COM_MSG_TAKE_SNAPSHOT_SUCCESS {
            get {
                return ResourceManager.GetString("COM_MSG_TAKE_SNAPSHOT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95-Update successfully..
        /// </summary>
        internal static string COM_MSG_UPDATE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_UPDATE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-This warehouse is inventorying..
        /// </summary>
        internal static string COM_MSG_WAREHOUSE_HAVING_COUNTSHEET {
            get {
                return ResourceManager.GetString("COM_MSG_WAREHOUSE_HAVING_COUNTSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-This warehouse is having stock..
        /// </summary>
        internal static string COM_MSG_WAREHOUSE_HAVING_STOCK {
            get {
                return ResourceManager.GetString("COM_MSG_WAREHOUSE_HAVING_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99-Main warehouse is not allow transfer wip.
        /// </summary>
        internal static string COM_MSG_WAREHOUSE_MAIN_NOT_TRANSFER_WIP {
            get {
                return ResourceManager.GetString("COM_MSG_WAREHOUSE_MAIN_NOT_TRANSFER_WIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Structure Management &gt; Departments &gt; Copy.
        /// </summary>
        internal static string MS_Departments_Copy {
            get {
                return ResourceManager.GetString("MS_Departments_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Structure Management &gt; Departments &gt; Edit.
        /// </summary>
        internal static string MS_Departments_Edit {
            get {
                return ResourceManager.GetString("MS_Departments_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Structure Management &gt; Departments &gt; New.
        /// </summary>
        internal static string MS_Departments_New {
            get {
                return ResourceManager.GetString("MS_Departments_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Structure Management &gt; Departments.
        /// </summary>
        internal static string MS_Departments_Search {
            get {
                return ResourceManager.GetString("MS_Departments_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Structure Management &gt; Departments &gt; Details.
        /// </summary>
        internal static string MS_Departments_View {
            get {
                return ResourceManager.GetString("MS_Departments_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Item Management &gt; Items &gt; Copy.
        /// </summary>
        internal static string MS_Items_Copy {
            get {
                return ResourceManager.GetString("MS_Items_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Item Management &gt; Items &gt; Edit.
        /// </summary>
        internal static string MS_Items_Edit {
            get {
                return ResourceManager.GetString("MS_Items_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Item Management &gt; Items &gt; Add.
        /// </summary>
        internal static string MS_Items_New {
            get {
                return ResourceManager.GetString("MS_Items_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Item Management &gt; Items.
        /// </summary>
        internal static string MS_Items_Search {
            get {
                return ResourceManager.GetString("MS_Items_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master &gt; Item Management &gt; Items &gt; Detail.
        /// </summary>
        internal static string MS_Items_View {
            get {
                return ResourceManager.GetString("MS_Items_View", resourceCulture);
            }
        }
    }
}
